### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Deraen**
This contains the same two first commits as my other PR.

This is a more complete refactor. The core idea is that the `core` namespace doesn't have any global state. Instead `start` functions returns a map containing the server state which can be passed to the `stop` function. Start function is parametrized so that it should be useful for many different use cases (e.g. Boot task).

`server` namespace contains `start!` and `stop!` functions which can be used when only one instance of LiveReload server is desired.

If no paths are given, watch service is not used. Instead `send-reload-msg` can be used. (e.g. Boot contains integrated watch service which is used for boot task instead).
- Sends reload messages for other than css files (html, js, images...)
- Multiple paths can be specified

### CODE REVIEW

**Comment by bhurlow** [comment]
@Deraen all this looks really good! At first I was working on this as a utility that I would require into each project. I eventually found it easier to use a [standalone](https://www.npmjs.com/package/livereload) in a language with a quicker boot time. The Boot task is a good idea though.

**Comment by bhurlow** [comment]
do you want this up on clojars then?

**Comment by Deraen** [comment]
@bhurlow Yes, would be nice :)

**Comment by Deraen** [comment]
ping @bhurlow Could do the release?

**Comment by bhurlow** [comment]
@Deraen https://clojars.org/clj-livereload

**Pull request merged**
